# Nom du workflow
name: Envoi_mail

on:
  workflow_dispatch:
  
# que fait le workflow

jobs:
    envoi_mail:
      permissions:
        contents: write
        pages: write
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.0
          with:
            name: mon_rapport.pdf
            path: mon_rapport.pdf

        - name: Envoi de mail
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com
            server_port: 465
            secure: true
            username: ${{secrets.MAIL_USERNAME_GHA}}
            password: ${{secrets.MAIL_PASSWORD_GHA}}
            subject: Le Tableau recapitulatif du jour
            to: armanddavy7@gmail.com
            from: TRE BI Armand Davy
            body: Veuillez trouver ci-joint le tableau recapitulatif de la situation de la collecte de ce jour
            cc: ilgatbad@gmail.com
            ignore_cert: true
            convert_markdown: true
            attachments: mon_rapport.pdf
            priority: low