on:
  workflow_dispatch:

jobs:
  generate-pdf:
        runs-on: ubuntu-22.04
        timeout-minutes: 10
        steps:
        - uses: actions/checkout@v4
          timeout-minutes: 5

        - name: Install R
          uses: r-lib/actions/setup-r@v2
        - name: Install packages
          uses: r-lib/actions/setup-r-dependencies@v2
          with:
            packages: |
              any::knitr
              any::rmarkdown
              any::downlit
              any::xml2
              any::gt
              any::tidyverse

        - name: Setup Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            tinytex: true
        - name: Check chromium
          run: |
            echo $(which chromium-browser)
            $(which chromium-browser) --headless https://www.chromestatus.com
        - name: Render Quarto Project
          uses: quarto-dev/quarto-actions/render@v2
          with:
            to: pdf
            path: mon_rapport.qmd
    
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.0
          with:
            name: mon_rapport.pdf
            path: mon_rapport.pdf

        - name: Commit results
          run: |
            git config --local user.email "armanddavy7@gmail.com"
            git config --local user.name "trebi7"
            git add mon_rapport.pdf
            git commit -m 'Rapport updated' || echo "No changes to commit"
            git push origin || echo "No changes to commit"
